### PR TITLE
Modified the username field length

### PR DESCRIPTION
**Pull request by kdpisda**
Increased the length of the username field in the user model as 20 is a bit low, I can't even use UUID or email for the username field as it break it.

### CODE REVIEW

**Review by moritz89 — APPROVED** [review]
Minor change that has a positive change. No side-effects expected

**Comment by moritz89** [comment]
I expect this would simply be a patch version increment 2.0.3?

**Comment by moritz89** [comment]
@uw-rvitorino @diogosilva30 Wanted to ask if the MR can be merged if the commit is replaced by a signed one? This change could be released with the other opened dependabot MRs

**Comment by kdpisda** [comment]
Any updates here?

**Comment by moritz89** [comment]
I've created the MR to fix it, but the UrbanPlatform team was gone completely silent. Could even reach them via other communication means :shrug:

**Review by uw-rvitorino — APPROVED** [review]

**Pull request merged**
